# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: APT | Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
