# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# defaults file for cloud

vagrant_version: 2.2.2
vagrant_linux_download_url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip
vagrant_darwin_download_url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.dmg
vagrant_win_download_url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.msi
vagrant_dir: /home/{{ user }}/bin

# packer_version: 1.3.3
# packer_linux_package_name: "packer_{{ packer_version }}_linux_amd64.zip"
# packer_linux_checksum: "sha256:2e3ea8f366d676d6572ead7e0c773158dfea0aed9c6a740c669d447bcb48d65f"
# packer_linux_download_url: https://releases.hashicorp.com/packer/{{ packer_version }}/{{ packer_linux_package_name }}
# packer_linux_dir: /home/{{ user }}/bin
# packer_darwin_package_name: "packer_{{ packer_version }}_darwin_amd64.zip"
# packer_darwin_checksum: "sha256:6ffbb13bee76e02f7b065955307d454b14773feee9fcfc3b5dd96ed154b931c4"
# packer_darwin_download_url: https://releases.hashicorp.com/packer/{{ packer_version }}/{{ packer_darwin_package_name }}
# packer_darwin_dir: /Users/{{ user }}/bin/

pkenv_version: 0.5.0
pkenv_linux_package_name: pkenv-{{ pkenv_version }}-1-x86_64.pkg.tar.xz
pkenv_linux_package_download_url: https://github.com/nlamirault/archlinux-packages/releases/download/v0.2.0/{{ pkenv_linux_package_name }}

# terraform_version: 0.11.11
# terraform_linux_package_name: terraform_{{ terraform_version }}_linux_amd64.zip
# terraform_linux_checksum: "sha256:94504f4a67bad612b5c8e3a4b7ce6ca2772b3c1559630dfd71e9c519e3d6149c"
# terraform_linux_download_url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_linux_package_name }}
# terraform_linux_dir: /home/{{ user }}/bin
# terraform_darwin_package_name: terraform_{{ terraform_version }}_darwin_amd64.zip
# terraform_darwin_checksum: "sha256:6b6e8253b678554c67d717c42209fd857bfe64a1461763c05d3d1d85c6f618d3"
# terraform_darwin_download_url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_darwin_package_name }}
# terraform_darwin_dir: /Users/{{ user }}/bin/

tfenv_version: 2.0.0_alpha3
tfenv_linux_package_name: tfenv-v{{ tfenv_version }}-1-x86_64.pkg.tar.xz
tfenv_linux_package_download_url: https://github.com/nlamirault/archlinux-packages/releases/download/v0.2.0/{{ tfenv_linux_package_name }}

vault_version: 1.0.1
vault_linux_package_name: "vault_{{ vault_version }}_linux_amd64.zip"
vault_linux_checksum: "sha256:1ea02627d0157dc844012995123f1cde86a02cb3b45030a9526057d12ee8d924"
vault_linux_download_url: https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_linux_package_name }}
vault_linux_dir: /home/{{ user }}/bin
vault_darwin_package_name: "vault_{{ vault_version }}_linux_amd64.zip"
vault_darwin_checksum: "sha256:10c1c3a0071dc0d50c2751027def3a0011a003e573bb9586cb34b7dee32e3d6d"
vault_darwin_download_url: https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_darwin_package_name }}
vault_darwin_dir: /Users/{{ user }}/bin/

kubernetes_cli_version: 1.13.0
kubernetes_cli_linux_download_url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_cli_version }}/bin/linux/amd64/kubectl
kubernetes_cli_linux_file: /home/{{ user }}/bin/kubectl
kubernetes_cli_darwin_download_url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_cli_version }}/bin/darwin/amd64/kubectl
kubernetes_cli_darwin_file: /Users/{{ user }}/bin/kubectl

# minikube_version: 0.32.0
# minikube_linux_checksum: "sha256:3298d3183deacd9ddd3032dab113a64d863df7648d6d24693284ba4193e95b49"
# minikube_linux_download_url: https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube-linux-amd64
# minikube_linux_file: /home/{{ user }}/bin/minikube
# minikube_darwin_download_url: https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube-darwin-amd64
# minikube_darwin_checksum: "sha256:d5b21adacd4b6bad9006816e4bdb29f39318a60919e7a6bb5e388a6299fffd0f"
# minikube_darwin_file: /Users/{{ user }}/bin/minikube

gcloud_sdk_version: 245.0.0
gcloud_sdk_base_url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads
gcloud_sdk_linux_dir: /home/{{ user }}/Applications
gcloud_sdk_linux_archive: google-cloud-sdk-{{ gcloud_sdk_version }}-linux-x86_64.tar.gz
gcloud_sdk_linux_download_url: "{{ gcloud_sdk_base_url }}/{{ gcloud_sdk_linux_archive }}"
gcloud_sdk_darwin_dir: /Users/{{ user }}/Applications
gcloud_sdk_darwin_archive: "google-cloud-sdk-{{ gcloud_sdk_version }}-darwin-x86_64.tar.gz"
gcloud_sdk_darwin_download_url: "{{ gcloud_sdk_base_url }}/{{ gcloud_sdk_linux_archive }}"
gcloud_sdk_win_dir: C:\Applications
gcloud_sdk_win_archive: "google-cloud-sdk-{{ gcloud_sdk_version }}-windows-x86_64.tar.gz"
gcloud_sdk_win_download_url: "{{ gcloud_sdk_base_url }}/{{ gcloud_sdk_linux_archive }}"

azure_cli_version: 2.0.70
azure_cli_dir: /home/{{ user }}/Applications/azure-cli/venv

aws_cli_version: 1.16.60
aws_cli_dir: /home/{{ user }}/Applications/aws-cli/venv

krew_version: 0.2.1
krew_package_name: krew.zip
krew_checksum: "sha256:57788e8c7af1b5b000954455aa9ca2e4a18a50a020faf54d18a3ccf79ad04049"
krew_download_url: https://storage.googleapis.com/krew/v{{ krew_version }}/{{ krew_package_name }}
krew_yaml_download_url: https://storage.googleapis.com/krew/v{{ krew_version }}/krew.yaml
krew_linux_file: krew-linux_amd64
krew_linux_dir: /home/{{ user }}/bin
krew_darwin_file: krew-darwin_amd64
krew_darwin_dir: /Users/{{ user }}/bin

# istio_version: 1.2.2
# istio_linux_package_name: istio-{{ istio_version }}-linux.tar.gz
# istio_linux_checksum: "sha256:a6ad3684d1b42901a526e7a755088b48402d7cd3420002fbbbb445a8a0117813"
# istio_linux_download_url: https://github.com/istio/istio/releases/download/{{ istio_version }}/{{ istio_linux_package_name }}
# istio_linux_dir: /home/{{ user }}/Applications
# istio_darwin_package_name: istio-{{ istio_version }}-osx.tar.gz
# istio_darwin_checksum: "sha256:46f12a808298e41191eea5a31780592d941fe843009dc6ae8d300edab2274135"
# istio_darwin_download_url: https://github.com/istio/istio/releases/download/{{ istio_version }}/{{ istio_darwin_package_name }}
# istio_darwin_dir: /Users/{{ user }}/bin
# istio_win_package_name: istio-{{ istio_version }}-win.zip
# istio_win_checksum: "sha256:054bd8293e12b8f0de37a3983d21a835bd700901b0336e5cc6d16da1f6da1a91"
# istio_win_download_url: https://github.com/istio/istio/releases/download/{{ istio_version }}/{{ istio_win_package_name }}

# linkerd_version: 2.2.0
# linkerd_linux_package_name: linkerd2-cli-stable-{{ linkerd_version }}-linux
# linkerd_linux_checksum: "sha256:4ce57680053f133043f3547181d7cc134b67ff7335e6765085c72e5d1b5a6e42"
# linkerd_linux_download_url: https://github.com/linkerd/linkerd2/releases/download/stable-{{ linkerd_version }}/{{ linkerd_linux_package_name }}
# linkerd_linux_file: /home/{{ user }}/bin/linkerd
# linkerd_darwin_package_name: linkerd2-cli-stable-{{ linkerd_version }}-darwin
# linkerd_darwin_checksum: "sha256:42dfdd2ab58b13230748f67d861cc08600c667a062ab8eb3d1a0c17ebbcb55d3"
# linkerd_darwin_download_url: https://github.com/linkerd/linkerd2/releases/download/stable-{{ linkerd_version }}/{{ linkerd_darwin_package_name }}
# linkerd_darwin_file: /Users/{{ user }}/bin/linkerd
# linkerd_win_package_name: linkerd2-cli-stable-{{ linkerd_version }}-windows.exe
# linkerd_win_checksum: "sha256:00d89ca10abd9db5fcb6b43e40f8cdc1d3e25582f3a4e3e6eec502d36922ed07"
# linkerd_win_download_url: https://github.com/linkerd/linkerd2/releases/download/stable-{{ linkerd_version }}/{{ linkerd_darwin_package_name }}
# linkerd_win_file: C:\

# kustomize_version: 2.0.3
# kustomize_linux_package_name: kustomize_{{ kustomize_version }}_linux_amd64
# kustomize_linux_checksum: "sha256:a04d79a013827c9ebb0abfe9d41cbcedf507a0310386c8d9a7efec7a36f9d7a3"
# kustomize_linux_download_url: https://github.com/kubernetes-sigs/kustomize/releases/download/v{{ kustomize_version }}/{{ kustomize_linux_package_name }}
# kustomize_linux_file: /home/{{ user }}/bin/kustomize
# kustomize_darwin_package_name: kustomize_{{ kustomize_version }}_darwin_amd64
# kustomize_darwin_checksum: "sha256:da4e4b7fe785a25997a0c34708faa6bce13d7847fc4d19d9ce46a0794098ba9b"
# kustomize_darwin_download_url: https://github.com/kubernetes-sigs/kustomize/releases/download/v{{ kustomize_version }}/{{ kustomize_darwin_package_name }}
# kustomize_darwin_file: /Users/{{ user }}/bin/kustomize

kzenv_version: 0.4.0
kzenv_linux_package_name: kzenv-{{ kzenv_version }}-1-x86_64.pkg.tar.xz
kzenv_linux_package_download_url: https://github.com/nlamirault/kzenv/releases/download/v{{ kzenv_version }}/{{ kzenv_linux_package_name }}

kind_version: 0.0.1
kind_linux_package_name: kind-linux-amd64
kind_linux_download_url: https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/{{ kind_linux_package_name }}
kind_linux_file: /home/{{ user }}/bin/kind
kind_darwin_package_name: kind-darwin-amd64
kind_darwin_download_url: https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/{{ kind_darwin_package_name }}
kind_darwin_file: /Users/{{ user }}/bin/kind

# eksctl_version: 0.2.1
# eksctl_linux_package_name: eksctl_Linux_amd64.tar.gz
# eksctl_linux_checksum: "sha256:0ebf82eae20cd1a0cf38cf3aadee759d93300b6b26ca23ca4fd0c7a564dcca41"
# eksctl_linux_download_url: https://github.com/weaveworks/eksctl/releases/download/{{ eksctl_version }}/{{eksctl_linux_package_name }}
# eksctl_linux_dir: /home/{{ user }}/Applications
# eksctl_darwin_package_name: eksctl_Darwin_amd64.tar.gz
# eksctl_darwin_checksum: "sha256:d5c40b196b431651b8ef06c03bd8d5b4bc084eb7d5a1d489be09d486a7895f64"
# eksctl_darwin_download_url: https://github.com/weaveworks/eksctl/releases/download/{{ eksctl_version }}/{{ eksctl_darwin_package_name }}
# eksctl_darwin_dir: /Users/{{ user }}/bin
# eksctl_win_package_name: eksctl_Windows_amd64.zip
# eksctl_win_checksum: "sha256:f6bb4d53637ec04cb2b4253d4fb432bf6831036f95e4d0d918f2253b08fd4451"
# eksctl_win_download_url: https://github.com/weaveworks/eksctl/releases/download/{{ eksctl_version }}/{{ eksctl_win_package_name }}
