# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Pacman | Update database
  community.general.pacman:
    update_cache: true

- name: Emacs | Install
  community.general.pacman:
    name: emacs
    state: present

- name: Neovim | Install
  community.general.pacman:
    name: neovim
    state: present
