# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Emacs | Install
  ansible.builtin.yum:
    name: emacs
    state: present

- name: Neovim | Install
  ansible.builtin.yum:
    name: neovim
    state: present
