---
- name: APT | Update database
  ansible.builtin.apt:
    update_cache: true

- name: Emacs | Install
  ansible.builtin.apt:
    name: emacs
    state: present

- name: Neovim | Install
  ansible.builtin.apt:
    name: neovim
    state: present
