# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: APT | Update database
  ansible.builtin.apt:
    update_cache: true

- name: Emacs | Install
  ansible.builtin.apt:
    name: emacs
    state: present

- name: Neovim | Install
  ansible.builtin.apt:
    name: neovim
    state: present
