---
- name: Emacs | Install
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - emacs

- name: Neovim | Install
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - neovim
      - python2-neovim
      - python3-neovim
