# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#ansible-distribution

---
- name: Include OS-specific tasks
  when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Ubuntu', 'Fedora', 'Linux Mint']
  become: true
  become_user: root
  block:
    - name: Editors | Core
      ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
    - name: Editors | Binaries
      ansible.builtin.include_tasks: linux.yml
