# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# Labels for action/labeler

area/ansible:
- changed-files:
  - any-glob-to-any-file: defaults/*
- changed-files:
  - any-glob-to-any-file: tasks/*
- changed-files:
  - any-glob-to-any-file: handlers/*
- changed-files:
  - any-glob-to-any-file: vars/*
