# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Include OS-specific tasks
  when: (ansible_distribution == 'Archlinux' or
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Debian' or
    ansible_distribution == 'Ubuntu' or
    ansible_distribution == 'Fedora' or
    ansible_distribution == 'MacOSX' or
    ansible_distribution == 'Windows')
  become: true
  become_user: root
  block:
    - name: Cloud | Core
      ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
