# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - '--allow-multiple-documents'
    exclude: mkdocs.yml
  -   id: check-added-large-files
# - repo: https://github.com/ansible-community/ansible-lint.git
#   rev: v6.9.1
#   hooks:
#     - id: ansible-lint
#     #   files: \.(yaml|yml)$
#       # do not pass files to ansible-lint, see:
#       # https://github.com/ansible-community/ansible-lint/issues/611
- repo: local
  hooks:
  - id: hawkeye
    name: "📄 Hawkeye / Insert license header"
    entry: bash -c 'hawkeye format'
    language: system
    pass_filenames: true
    files: \.*$
    args: []
