---
- name: Install | X utilities
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libglvnd
      - xorg-server
      - xorg-xinit
      - arandr
      - accountsservice
      - slim
      - slim-themes
      - archlinux-themes-slim
      # - lxdm
      # - lxdm-gtk3
      - sddm
      # - lightdm
      # - lightdm-gtk-greeter-settings
      # - lightdm-webkit2-greeter
      # - lightdm-webkit-theme-litarvan
      # - light-locker
      - xss-lock
      - clipmenu
      - clipnotify

- name: Display | Create sddm custom configuration directory
  ansible.builtin.file:
    path: /etc/sddm.conf.d/
    state: directory
    mode: 0755

- name: Systemd | Enable display manager
  ansible.builtin.service:
    name: sddm
    enabled: yes
  ignore_errors: yes

- name: Systemd | Start display manager
  ansible.builtin.service:
    name: sddm
    state: started
  ignore_errors: yes

# - name: Install web browsers (with Yay)
#   kewlfft.aur.aur:
#     name: "{{ packages }}"
#     use: makepkg
#     state: present
#   become: yes
#   become_user: aur_builder
#   vars:
#     packages:
#       - google-chrome-beta
#       # - brave

- name: Install | Graphics applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - inkscape
      - flameshot

- name: Install | Video applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc
      - libmicrodns # For Chromecast

- name: Install | Music applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - pulseaudio
      - pavucontrol
      - pulsemixer
      - playerctl

# - name: Install music applications with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - spotify

- name: Install | Communications applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi
      - vinagre
      - rdesktop

# - name: Install communications applications with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - slack-desktop
#       - zoom

- name: Install | Documentation applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - evince
      - mupdf

- name: Install | Fonts
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - awesome-terminal-fonts
      # - ttf-symbola

# - name: Install fonts with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - nerd-fonts-hack

- name: Install | Security tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openvpn
      - wireguard-tools
      - keepassxc
      - arch-audit

- name: Install | Torrent tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - deluge
      - fragments
      - transmission-gtk
      - transmission-cli

# - name: Install cloud development tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - direnv-bin
#       - tfenv
#       - tgenv

# - name: Install network tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - iwtk

- name: Install | Bluetooth tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bluez
      - bluez-utils
      - bluez-tools
      - blueman
      - gnome-bluetooth
  # notify:
  #   - Bluetooth service

- name: System | Enable bluetooth service
  ansible.builtin.service:
    enabled: yes
    name: bluetooth

- name: System | Bluetooth service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: bluetooth
