# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Install | X utilities
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libglvnd
      - xorg-server
      - xorg-xinit
      - arandr
      - accountsservice
      - slim
      - slim-themes
      - archlinux-themes-slim
      - sddm
      - xss-lock
      - clipmenu
      - clipnotify

- name: Display | Create sddm custom configuration directory
  ansible.builtin.file:
    path: /etc/sddm.conf.d/
    state: directory
    mode: 0755

- name: Systemd | Enable display manager
  ansible.builtin.service:
    name: sddm
    enabled: true
  failed_when: false

- name: Systemd | Start display manager
  ansible.builtin.service:
    name: sddm
    state: started
  failed_when: false

- name: Install | Graphics applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - inkscape
      - flameshot

- name: Install | Video applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc
      - libmicrodns

- name: Install | Music applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - pulseaudio
      - pavucontrol
      - pulsemixer
      - playerctl

- name: Install | Communications applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi
      - vinagre
      - rdesktop

# - name: Install communications applications with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - slack-desktop
#       - zoom

- name: Install | Documentation applications
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - evince
      - mupdf

- name: Install | Fonts
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - awesome-terminal-fonts
      # - ttf-symbola

# - name: Install fonts with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - nerd-fonts-hack

- name: Install | Security tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openvpn
      - wireguard-tools
      - keepassxc
      - arch-audit

- name: Install | Torrent tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - deluge
      - fragments
      - transmission-gtk
      - transmission-cli

# - name: Install cloud development tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - direnv-bin
#       - tfenv
#       - tgenv

# - name: Install network tools with Yay
#   community.general.pacman:
#     name: "{{ packages }}"
#     state: present
#     executable: yay
#     # extra_args: --builddir /var/cache/yay
#   vars:
#     packages:
#       - iwtk

- name: Install | Bluetooth tools
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bluez
      - bluez-utils
      - bluez-tools
      - blueman
      - gnome-bluetooth

- name: System | Enable bluetooth service
  ansible.builtin.service:
    enabled: true
    name: bluetooth

- name: System | Bluetooth service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: bluetooth
