# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Install X
  ansible.builtin.apt:
    state: present
    name:
      - xinit
      - gdm3

- name: Apt | Add Apt signing key
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Apt | Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install web applications
  ansible.builtin.apt:
    state: present
    name:
      - google-chrome-stable
      - google-chrome-beta

- name: Install graphics applications
  ansible.builtin.apt:
    state: present
    name:
      - gimp
      - inkscape

- name: Install video applications
  ansible.builtin.apt:
    state: present
    name:
      - vlc

- name: Install communications applications
  ansible.builtin.apt:
    state: present
    name:
      - irssi
      - vinagre
      - rdesktop

- name: Install documentation applications
  ansible.builtin.apt:
    state: present
    name:
      - libreoffice
      - evince
