---
- name: Install web applications
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - chromium-browser

- name: Install multimedia applications
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - inkscape

- name: Install video applications
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - vlc

- name: Install communications applications
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi
      - vinagre
      - rdesktop

- name: Install documentation applications
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - evince

# TODO: Install Keepassxc for LinuxMint
# - name: Add Keepassxc PPA
#   apt_repository: repo=ppa:phoerious/keepassxc

# - name: Install security tools
#   ansible.builtin.apt: pkg={{ packages }} state=present update_cache=yes
#   with_packagess:
#     - keepassxc
