# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html#ansible-distribution

---
- name: Include OS-specific tasks
  when: (ansible_distribution == 'Archlinux' or
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Debian' or
    ansible_distribution == 'Ubuntu' or
    ansible_distribution == 'Fedora' or
    ansible_distribution == 'Linux Mint')
  become: true
  become_user: root
  block:
    - name: Desktop | Core
      ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
    - name: Desktop | X11
      ansible.builtin.include_tasks: x11.yml
