---
- name: Include OS-specific tasks
  block:
    - include_tasks: "{{ ansible_distribution }}.yml"
  when: (ansible_distribution == 'Archlinux' or
         ansible_distribution == 'CentOS' or
         ansible_distribution == 'Debian' or
         ansible_distribution == 'Fedora' or
         ansible_distribution == 'Linux Mint')
  become: true
  become_user: root

- name: X11 for Linux
  block:
    - include_tasks: x11.yml
  when: (ansible_distribution == 'Debian' or
         ansible_distribution == 'Archlinux')
  become: true
  become_user: root
