---
- name: WindowManager | Install i3 and tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - i3
      - i3lock
      - i3status
      - dmenu
      - xbacklight

- name: WindowManager | Install commons tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - conky
