# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: APT | Update database
  ansible.builtin.apt:
    update_cache: true

- name: Packages | Install base tools
  ansible.builtin.apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - bash-completion
      - tar
      - git
      - unzip
      - lsb-release

- name: Packages | Install shell tools
  ansible.builtin.apt:
    state: present
    name:
      # - debianutils
      - bash-completion
      - tree
      - tmux
      - ncdu

- name: Packages | Install terminal emulators
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - terminator

- name: Packages | Install networks tools
  ansible.builtin.apt:
    state: present
    name:
      - openssh-server
      - wget
      - curl
      - ngrep
