---
- name: APT | Update database
  apt:
    update_cache: true

- name: Packages | Install shell tools
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - debianutils
      - bash-completion
      - tree
      - tmux
      - ncdu

- name: Packages | Install terminal emulators
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - terminator

- name: Packages | Install networks tools
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openssh-server
      - wget
      - curl
      - ngrep

- name: Packages | Install defaults packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bash-completion
      - git
      - unzip
      - logrotate
      - rsyslog
