# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Packages | Install shell tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bash-completion
      - fzf
      - tree
      - tmux
      - ncdu
      - feh

- name: Packages | Install terminal emulators
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - terminator

- name: Packages | Install network tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openssh
      - wget
      - curl
      - ngrep

- name: Packages | Install defaults packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - man-db
      - dunst
      - git
      - gnupg
      - tig
      - unzip
      - logrotate
      - rsyslog
      - sysstat
      - mlocate
      - ccze

- name: Packages | Install modern Unix tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fd-find
