# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
- name: Debug | Operating System
  ansible.builtin.debug:
    msg: System {{ ansible_distribution }}

- name: Directories for Unix
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Linux Mint', 'Archlinux', 'CentOS', 'Fedora']
  become: true
  become_user: root
  block:
    - name: Base | Unix directories
      ansible.builtin.include_tasks: unix.yml
    - name: Base | Core
      ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Tools for Archlinux
  when: ansible_distribution == 'Archlinux'
  block:
    - name: Base | Archlinux specific
      ansible.builtin.include_tasks: arch_tools.yml
