# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# defaults file for editors

vscode_name: "VSCode-linux-x64"
vscode_version: 1.73.1
vscode_download_url: https://update.code.visualstudio.com/{{ vscode_version }}/linux-x64/stable
vscode_dir: /home/{{ user }}/Applications
