# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Ansible / Lint

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 0

    - name: ✅ Lint Ansible Playbook
      uses: ansible-actions/ansible-lint-action@f32438707106decdb067a067e4f026c0e94e3f16 # v1.1.0
      with:
        target: "./"
