# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Ansible / Lint

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: ✅ Lint Ansible Playbook
      uses: ansible-actions/ansible-lint-action@f32438707106decdb067a067e4f026c0e94e3f16 # v1.1.0
      with:
        args: ""
        targets: ""
