# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Project / Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
    - main

permissions:
  contents: write         # to push tags and changelog
  issues: write           # (optional) for any issue linkage
  pull-requests: write    # to create/modify the release PR

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Run Release Please Action
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: ${{ github.ref_name }}
        config-file: .github/release-please-config.json
